project:
  type: website
  output-dir: docs
  

website:
  title: "dashboards"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - icon: github
        href: https://github.com/reimn11
        target: blank

format:
  html:
    theme:
      - solar
      - brand
    css: styles.css
    toc: true

editor: visual

